version: "3.9"

services:
  pigmon-db:
    build: ./env/mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
      TZ: Asia/Tokyo
    volumes:
      - ./env/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3315:3306"

  pigmon-frontend:
    build:
      context: .
      dockerfile: ./env/react/Dockerfile
    container_name: react_container
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true
    volumes:
    - ./src/react-app:/app/react/react-app
    command: sh -c "cd /app/react/react-app  && yarn start"
    ports:
      - 3000:3000

  pigmon-backend:
    build:
      context: .
      dockerfile: ./env/golang/Dockerfile
    tty: true
    container_name: go_container
    environment:
      APP_MODE: local
      DB_USER: mysqluser
      DB_PASSWORD: mysqlpass
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: pigmon
      DB_NAME_TEST: pigmon_test
      DB_LOC: Asia%2FTokyo
    volumes:
      - "./src/go-app:/go/src/pigmon/go-app"
    ports:
      - 9000:9000
    depends_on:
      - db
    command: "realize start"

  pigmon-nginx:
    image: nginx
    container_name: nginx_container
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./env/nginx/nginx.conf:/etc/nginx/nginx.conf