FROM node:16-alpine
WORKDIR /app/react
RUN npm install --save prop-types
RUN npm install -g create-react-app
RUN npm install axios
RUN npm i @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^4